version: '3.6'
services: 
  auth:
    build:
      args:
        - NODE_ENV=production
    restart: unless-stopped

  graphql-engine:
    restart: always

  nginx:
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
