version: '3.6'
services: 
  migration:
    image: "${MIGRATION_IMAGE}"
  
  graphql-engine:
    restart: unless-stopped

  auth:
    image: "${AUTH_IMAGE}"
    build:
      args:
        - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: "${NGINX_IMAGE}"
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      - NODE_ENV=production
      - APP_ENV=prod
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
