defaultEntryPoints = ["https","http"]

[api]
entryPoint = "dashboard"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth.basic]
    users = ["khoa:$apr1$D4Notp8i$tbUMHR.JquaEIJWCoaPwo/"]
    
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "/cloudflare.cert"
    keyfile = "/cloudflare.key"

[docker]
domain = "docker.localhost"
watch = true
network = "web"

[retry]
