name: Build and deploy

on: [push]

env:
  AUTH_IMAGE: docker.pkg.github.com/$GITHUB_REPOSITORY/auth:$COMMIT_SHA
  MIGRATION_IMAGE: docker.pkg.github.com/$GITHUB_REPOSITORY/migration:$COMMIT_SHA
  NGINX_IMAGE: docker.pkg.github.com/$GITHUB_REPOSITORY/nginx:$COMMIT_SHA

jobs:

  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo DEBUG=0 >> .env
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
      - name: Push images
        run: |
          docker push ${{ AUTH_IMAGE }}
          docker push ${{ MIGRATION_IMAGE }}
          docker push ${{ NGINX_IMAGE }}