name: Build and deploy

on: [push]

env:
  DOCKER_LOGIN_COMMAND: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

jobs:
  deploy:
    environment: Production
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Set environment variables
        run: |
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')
          echo AUTH_IMAGE=docker.pkg.github.com/${REPOSITORY}/auth:${GITHUB_SHA} >> $GITHUB_ENV
          echo MIGRATION_IMAGE=docker.pkg.github.com/${REPOSITORY}/migration:${GITHUB_SHA} >> $GITHUB_ENV
          echo NGINX_IMAGE=docker.pkg.github.com/${REPOSITORY}/nginx:${GITHUB_SHA} >> $GITHUB_ENV
      - name: Add environment variables to .env
        run: |
          echo HASURA_ACCESS_KEY=${{ secrets.HASURA_ACCESS_KEY }} >> .env
          echo AUTH_GITHUB_CLIENT_ID=${{ secrets.AUTH_GITHUB_CLIENT_ID }} >> .env
          echo AUTH_GITHUB_CLIENT_SECRET=${{ secrets.AUTH_GITHUB_CLIENT_SECRET }} >> .env
          echo AUTH_GITHUB_CALLBACK_URL=${{ secrets.AUTH_GITHUB_CALLBACK_URL }} >> .env
          echo AUTH_URL=${{ secrets.AUTH_URL }} >> .env
          echo FRONTEND_URL=${{ secrets.FRONTEND_URL }} >> .env
          echo JWT_TOKEN=${{ secrets.JWT_TOKEN }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo AUTH_IMAGE=${{ env.AUTH_IMAGE }} >> .env
          echo MIGRATION_IMAGE=${{ env.MIGRATION_IMAGE }} >> .env
          echo NGINX_IMAGE=${{ env.NGINX_IMAGE }} >> .env
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DIGITAL_OCEAN_KEY }}" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName ${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }}
            User ${{ secrets.DIGITAL_OCEAN_USER }}
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
      - name: Log into registry
        run: ssh production "$DOCKER_LOGIN_COMMAND"
      - name: Build and deploy images on DigitalOcean
        run: |
          scp production -r ./.env ./docker-compose.yml ./docker-compose.prod.yml ~/app
          ssh production << 'ENDSSH'
            cd app
            source .env
            docker login -u ${GITHUB_ACTOR} -p {GITHUB_TOKEN} docker.pkg.github.com
            docker pull ${AUTH_IMAGE}
            docker pull ${MIGRATION_IMAGE}
            docker pull ${NGINX_IMAGE}
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
          ENDSSH